project:
  name: crocs

paths:
  raw_data_dir: data/raw
  output_dir: data/output
  forecast_input_dir: data/output

inputs:
  train: train.csv
  reqlabor: reqlabor.csv

outputs:
  forecast: forecast.xlsx

forecast:
  start: 2026-04-27
  end: 2026-05-03
  open_hour: 7
  close_hour: 23
  guests_source: file
